CREATE DATABASE BDESTACIONAMENTO;

USE BDESTACIONAMENTO;

CREATE TABLE TBCATEGORIA (
IDCAT INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
PRECO_PRIMEIRA_HORA DECIMAL(5,2) NOT NULL,
PRECO_HORAS_ADICIONAIS DECIMAL(5,2) NOT NULL,
PRECO_DIARIA DECIMAL(5,2) NOT NULL
);

CREATE TABLE TBCLIENTE (
IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMECLIENTE VARCHAR(30) NOT NULL,
TELEFONECLIENTE VARCHAR(14) NOT NULL,
CPFCLIENTE VARCHAR(14) NOT NULL UNIQUE
);

CREATE TABLE TBVEICULO (
IDVEICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CODCLIENTE INT NULL,
PLACAVEICULO VARCHAR (7) NOT NULL UNIQUE,
MODELOVEICULO VARCHAR(15) NOT NULL,
TIPOVEICULO VARCHAR(10) NOT NULL,
FOREIGN KEY (CODCLIENTE) REFERENCES TBCLIENTE (IDCLIENTE) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE TBFUNCIONARIO (
IDFUNCI INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
SENHAFUNCI INT NOT NULL UNIQUE,
TELEFONEFUNCI VARCHAR(14) NOT NULL,
EMAILFUNCI VARCHAR(50) NOT NULL,
CPFFUNCI VARCHAR(14) NOT NULL UNIQUE,
NOMEFUNCI VARCHAR(30) NOT NULL,
STATUSFUNCI VARCHAR(7) NOT NULL
);

CREATE TABLE TBSERVICO (
IDSERVICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CODCAT INT NOT NULL,
CODVEICULO INT NOT NULL,
CODFUNCI_ENTRADA INT NOT NULL,
CODFUNCI_SAIDA INT NULL,
DATAFINAL DATE NULL,
DATAINICIAL DATE NOT NULL,
HORAENTRADA TIME NOT NULL,
HORASAIDA TIME NULL,
VALORTOTAL DECIMAL(10,2) NULL,
STATUSSERVICO VARCHAR(15) NOT NULL,
FOREIGN KEY (CODCAT) REFERENCES TBCATEGORIA (IDCAT) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CODVEICULO) REFERENCES TBVEICULO (IDVEICULO) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CODFUNCI_ENTRADA) REFERENCES TBFUNCIONARIO (IDFUNCI) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CODFUNCI_SAIDA) REFERENCES TBFUNCIONARIO (IDFUNCI) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB;

INSERT INTO TBCATEGORIA (PRECO_PRIMEIRA_HORA,PRECO_HORAS_ADICIONAIS,PRECO_DIARIA) VALUES
(2.00,2.00,20.00);


INSERT INTO TBCLIENTE (NOMECLIENTE, TELEFONECLIENTE, CPFCLIENTE) VALUES
("KAUE CARVALHO", "17 99091-8954", "901.894.333-12"),
("LUIZ MELO", "65 98898-4598", "730.753.064-75"),
("LEONARDO DIAS", "19 95847-9237", "838.926.204-84"),
("LUIZA SANTOS", "21 99000-3754", "845.015.798-94"),
("MARIANA CUNHA", "10 93756-0365", "937.365.276-98"),
("DIOGO SOUZA", "28 99861-1563", "132.861.520-05"),
("CARLA RIBEIRO", "95 96791-1583", "179.720.187-58"),
("EDUARDA ROCHA", "96 98951-7229", "697.768.576-04"),
("LAURA RODRIGUES", "97 99971-0265", "640.544.509-70");

INSERT INTO TBVEICULO (CODCLIENTE,PLACAVEICULO,MODELOVEICULO,TIPOVEICULO) VALUES
(1,"BFX4281","HONDA CIVIC","CARRO"),
(2,"GEJ1526","HONDA","MOTO"),
(3,"DFJ2236","VOLKSWAGEN","CAMINHAO"),
(4,"CYT5860","VOLKSWAGEN","CARRO"),
(5,"EAY0834","COROLLA","CARRO"),
(6,"EDO7198","FIAT","CARRO"),
(7,"DON6272","YAMAHA","MOTO"),
(8,"DBW7759","NISSAN","CARRO"),
(9,"BUN3878","HONDA","MOTO"),
(9,"CRS8695","HYUNDAI","CARRO");

INSERT INTO TBFUNCIONARIO (SENHAFUNCI,TELEFONEFUNCI,EMAILFUNCI,CPFFUNCI,NOMEFUNCI,STATUSFUNCI) VALUES
("111111","13 2418-5853","CAROLINAALMEIDABARBOSA@ESTACIONAMENTO.COM.BR","440.984.373-76","CAROLINA ALMEIDA BARBOSA","ATIVO"),
("121212","81 7417-5612","ANNAARAUJOFERREIRA@ESTACIONAMENTO.COM.BR","165.001.792-85","ANNA ARAUJO FERREIRA","ATIVO"),
("131313","41 8569-3091","KAUAMELORIBEIRO@ESTACIONAMENTO.COM.BR","840.936.057-85","KAUA MELO RIBEIRO","ATIVO");

INSERT INTO TBSERVICO (CODCAT,CODVEICULO,CODFUNCI_ENTRADA,CODFUNCI_SAIDA,DATAFINAL,DATAINICIAL,HORAENTRADA,HORASAIDA,STATUSSERVICO) VALUES
(1, 1, 1, 1, "2025-08-29", "2025-08-29", "13:39:50", "22:08:30", "FINALIZADO"),
(1, 2, 2, 2, "2025-08-30", "2025-08-30", "10:08:32", "13:39:50", "FINALIZADO"),
(1, 3, 3, 3, "2025-08-31", "2025-08-31", "09:12:12", "09:35:47", "FINALIZADO"),
(1, 4, 1, 1, "2025-09-03", "2025-09-03", "08:03:05", "17:30:36", "FINALIZADO"),
(1, 5, 2, 2, "2025-09-03", "2025-09-03", "19:47:51", "23:39:17", "FINALIZADO"),
(1, 6, 3, 3, "2025-09-03", "2025-09-03", "15:51:21", "20:40:34", "FINALIZADO"),
(1, 7, 1, 1, "2025-09-03", "2025-09-03", "07:59:41", "13:12:08", "FINALIZADO"),
(1, 8, 2, 2, "2025-09-03", "2025-09-03", "08:47:06", "17:14:21", "FINALIZADO"),
(1, 9, 3, 1, "2025-09-03", "2025-09-04", "23:03:05", "00:04:57", "FINALIZADO"),
(1, 10, 1, 1, "2025-09-04", "2025-09-05", "17:59:17", "10:08:32", "FINALIZADO");

/*Consultar o nome do funcionário de ID=3 e quantidade de serviços feitos por ele no mês de setembro*/
SELECT F.NOMEFUNCI, COUNT(S.DATAINICIAL)
FROM tbfuncionario F
INNER JOIN tbservico S
ON F.IDFUNCI=S.CODFUNCI
WHERE F.IDFUNCI=3 AND S.DATAINICIAL BETWEEN "2025-09-01" AND "2025-09-30";

/*Consultar os nomem dos funcionários e quantidades de serviços feitos por eles*/
SELECT F.NOMEFUNCI, COUNT(S.DATAINICIAL)
FROM tbfuncionario F
INNER JOIN tbservico S
ON F.IDFUNCI=S.CODFUNCI
GROUP BY F.IDFUNCI;

/*Consultar os dados das tabelas TBCLIENTE e TBVEICULO mostrando o nome dos clientes que possuem carro e não possuem credencial.*/
SELECT C.NOMECLIENTE, V.MODELOVEICULO
FROM tbcliente C
INNER JOIN tbveiculo V
ON C.IDCLIENTE=V.CODCLIENTE
WHERE C.CREDENCLIENTE="N" AND V.TIPOVEICULO="CARRO";

/*Consulte os dados das tabelas TBSERVICOS, TBVAGA, TBCATEGORIA, TBVEICULO e TBCLIENTE usando INNER JOIN para mostrar vagas ocupadas no mês de agosto pelo respectivo cliente*/
SELECT V.NOMEVAGA, CLI.NOMECLIENTE
FROM tbservico S
INNER JOIN tbvaga V
ON V.IDVAGA=S.CODVAGA
INNER JOIN tbcategoria C
ON V.CODCAT=C.IDCAT
INNER JOIN tbveiculo VEI
ON VEI.IDVEICULO=S.CODVEICULO
INNER JOIN tbcliente CLI
ON CLI.IDCLIENTE=VEI.CODCLIENTE
WHERE C.VAGACAT = "COMUM" AND S.DATAFINAL BETWEEN "2025-08-01" AND "2025-08-31";

/*Consulte os dados das tabelas TBVAGA e TBCATEGORIA, como os tipos da vaga e o valor total(soma) de serviços realizados com cada tipo de vaga*/
SELECT C.VAGACAT,SUM(C.PRECOCAT)
FROM TBVAGA V
INNER JOIN TBCATEGORIA C
ON V.CODCAT=C.IDCAT
GROUP BY C.VAGACAT;

/*Consultar o modelo do veículo e a suas respectivas datas de entrada e saída para cada moto //obs: a profª Fabi disse não haver visto sentido nessa consulta*/
SELECT V.MODELOVEICULO, S.DATAINICIAL, S.DATAFINAL
FROM tbveiculo V
INNER JOIN tbservico S
ON V.IDVEICULO = S.CODVEICULO
WHERE V.TIPOVEICULO = "MOTO";

/*Status e nomes de todas as vagas no atual momento do Banco de Dados*/
SELECT V.NOMEVAGA, V.STATUSVAGA
FROM tbvaga V;

/*Calcula o total de horas e preço da estadia no estacionamento, a partir do preço por hora da vaga, mostrando o nome do cliente, a placa e modelo do veículo em ordem crescente*/
SELECT
    CLI.NOMECLIENTE AS CLIENTE,
    VEI.PLACAVEICULO AS PLACA,
    VEI.MODELOVEICULO AS MODELO,
 /* -- TIMESTAMPDIFF: função que calcula a diferença entre dois valores de data, hora ou carimbo de data/hora (timestamp);
    Retorna em um valor de intervalo de tempo horas, minutos, segundos, etc... */
    -- CONCAT: Concatena Strings, nesse caso está combinando DATE e TIME para formar um DATATIME.
    TIMESTAMPDIFF(MINUTE,
        CONCAT(S.DATAFINAL, ' ', S.HORAENTRADA),
        CONCAT(S.DATAINICIAL, ' ', S.HORASAIDA)
    )/60 AS DURACAO_EM_HORAS,
    -- calcula o custo Total: duração (em horas) * preço por hora
    CASE
    	WHEN
    (TIMESTAMPDIFF(MINUTE,
        CONCAT(S.DATAFINAL, ' ', S.HORAENTRADA),
        CONCAT(S.DATAINICIAL, ' ', S.HORASAIDA)
    )/60) < 1
    THEN CAT.PRECO_PRIMEIRA_HORA
	 
    ELSE
     CAT.PRECO_PRIMEIRA_HORA + CAT.PRECO_HORAS_ADICIONAIS*(TIMESTAMPDIFF(MINUTE,
        CONCAT(S.DATAFINAL, ' ', S.HORAENTRADA),
        CONCAT(S.DATAINICIAL, ' ', S.HORASAIDA)
    )/60)
    END AS PRECO_TOTAL
FROM
    tbservico S
INNER JOIN
    tbcategoria CAT ON CAT.IDCAT = S.CODCAT
INNER JOIN
    tbveiculo VEI ON VEI.IDVEICULO = S.CODVEICULO
INNER JOIN
    tbcliente CLI ON VEI.CODCLIENTE = CLI.IDCLIENTE
ORDER BY 
    S.IDSERVICO ASC;
    
